### ISSUE TITLE
I get this error on a custom theme

### ISSUE THREAD

**Issue by westernbees** [mrugeshrocks/Magehouse_PriceSlider2.2.0#1]
Uncaught ReferenceError: sliderAjax is not defined .

**Comment by mrugeshrocks** [comment]
Hi,

This issue comes when the layouts are not getting updated. 

This file must be included in the category page 

app/design/frontend/base/default/template/slider/ajax.phtml

Plugin is theme independent until the plugin files are moved :)

Try the following :
- Enable Use Ajax for price slider
- Clear the cache folder /var/cache/\* or flush the cache from admin.

Thanks.
